{ config, pkgs, ... }: 

{
  home.username = "artur";
  home.homeDirectory = "/home/artur";
  home.stateVersion = "24.11";

  home.packages = [
    pkgs.zoxide
    pkgs.oh-my-posh
    pkgs.neovim
    pkgs.bat
    pkgs.tmux
  ];

  home.file = {
    ".tmux.conf".source = ~/configs/tmux.conf;
  };

  home.file = {
    ".tmux/plugins/tpm" = {
      source = pkgs.fetchgit {
        url = "https://github.com/tmux-plugins/tpm";
        rev = "main";  # e.g., "main" or a specific commit
        sha256 = "sha256-hW8mfwB8F9ZkTQ72WQp/1fy8KL1IIYMZBtZYIwZdMQc=";  # The hash of the repository, which can be generated by running `nix-prefetch-git https://github.com/tmux-plugins/tpm`.
      };
    };
  };

  home.file = {
    ".bashrc".source = ''
      # Initialize zoxide
      eval "$(zoxide init bash)"
    '';
  };

  programs.home-manager.enable = true;
}
